2023-10-30 11:08:00,796 ERROR scheduler Exception in Enqueue Events for Site sona3elkhairerp.orbscopeapps.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/__init__.py", line 1480, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "apps/frappe/frappe/__init__.py", line 1342, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'hrms.hooks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 75, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 114, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "apps/frappe/frappe/utils/scheduler.py", line 127, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "apps/frappe/frappe/database/database.py", line 789, in get_single_value
    df = frappe.get_meta(doctype).get_field(fieldname)
  File "apps/frappe/frappe/__init__.py", line 1226, in get_meta
    return frappe.model.meta.get_meta(doctype, cached=cached)
  File "apps/frappe/frappe/model/meta.py", line 65, in get_meta
    meta = Meta(doctype)
  File "apps/frappe/frappe/model/meta.py", line 117, in __init__
    super().__init__("DocType", doctype)
  File "apps/frappe/frappe/model/document.py", line 107, in __init__
    self.load_from_db()
  File "apps/frappe/frappe/model/meta.py", line 123, in load_from_db
    super().load_from_db()
  File "apps/frappe/frappe/model/document.py", line 177, in load_from_db
    self.set(df.fieldname, children)
  File "apps/frappe/frappe/model/base_document.py", line 219, in set
    self.extend(key, value)
  File "apps/frappe/frappe/model/base_document.py", line 260, in extend
    self.append(key, v)
  File "apps/frappe/frappe/model/base_document.py", line 245, in append
    value = self._init_child(value, key)
  File "apps/frappe/frappe/model/base_document.py", line 274, in _init_child
    value = get_controller(doctype)(value)
  File "apps/frappe/frappe/model/base_document.py", line 89, in get_controller
    return _get_controller()
  File "apps/frappe/frappe/model/base_document.py", line 67, in _get_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "apps/frappe/frappe/__init__.py", line 1513, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", _load_app_hooks))
  File "apps/frappe/frappe/utils/redis_wrapper.py", line 81, in get_value
    val = generator()
  File "apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 1486, in _load_app_hooks
    print(f'Could not find app "{app}": \n{e}')
BrokenPipeError: [Errno 32] Broken pipe

2023-10-30 11:09:00,902 ERROR scheduler Exception in Enqueue Events for Site sona3elkhairerp.orbscopeapps.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/__init__.py", line 1480, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "apps/frappe/frappe/__init__.py", line 1342, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'hrms.hooks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 75, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 114, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "apps/frappe/frappe/utils/scheduler.py", line 127, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "apps/frappe/frappe/database/database.py", line 789, in get_single_value
    df = frappe.get_meta(doctype).get_field(fieldname)
  File "apps/frappe/frappe/__init__.py", line 1226, in get_meta
    return frappe.model.meta.get_meta(doctype, cached=cached)
  File "apps/frappe/frappe/model/meta.py", line 65, in get_meta
    meta = Meta(doctype)
  File "apps/frappe/frappe/model/meta.py", line 117, in __init__
    super().__init__("DocType", doctype)
  File "apps/frappe/frappe/model/document.py", line 107, in __init__
    self.load_from_db()
  File "apps/frappe/frappe/model/meta.py", line 123, in load_from_db
    super().load_from_db()
  File "apps/frappe/frappe/model/document.py", line 177, in load_from_db
    self.set(df.fieldname, children)
  File "apps/frappe/frappe/model/base_document.py", line 219, in set
    self.extend(key, value)
  File "apps/frappe/frappe/model/base_document.py", line 260, in extend
    self.append(key, v)
  File "apps/frappe/frappe/model/base_document.py", line 245, in append
    value = self._init_child(value, key)
  File "apps/frappe/frappe/model/base_document.py", line 274, in _init_child
    value = get_controller(doctype)(value)
  File "apps/frappe/frappe/model/base_document.py", line 89, in get_controller
    return _get_controller()
  File "apps/frappe/frappe/model/base_document.py", line 67, in _get_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "apps/frappe/frappe/__init__.py", line 1513, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", _load_app_hooks))
  File "apps/frappe/frappe/utils/redis_wrapper.py", line 81, in get_value
    val = generator()
  File "apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 1486, in _load_app_hooks
    print(f'Could not find app "{app}": \n{e}')
BrokenPipeError: [Errno 32] Broken pipe

2023-10-30 11:10:00,957 ERROR scheduler Exception in Enqueue Events for Site sona3elkhairerp.orbscopeapps.com
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/__init__.py", line 1480, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "apps/frappe/frappe/__init__.py", line 1342, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'hrms.hooks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 75, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 114, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "apps/frappe/frappe/utils/scheduler.py", line 127, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "apps/frappe/frappe/database/database.py", line 789, in get_single_value
    df = frappe.get_meta(doctype).get_field(fieldname)
  File "apps/frappe/frappe/__init__.py", line 1226, in get_meta
    return frappe.model.meta.get_meta(doctype, cached=cached)
  File "apps/frappe/frappe/model/meta.py", line 65, in get_meta
    meta = Meta(doctype)
  File "apps/frappe/frappe/model/meta.py", line 117, in __init__
    super().__init__("DocType", doctype)
  File "apps/frappe/frappe/model/document.py", line 107, in __init__
    self.load_from_db()
  File "apps/frappe/frappe/model/meta.py", line 123, in load_from_db
    super().load_from_db()
  File "apps/frappe/frappe/model/document.py", line 177, in load_from_db
    self.set(df.fieldname, children)
  File "apps/frappe/frappe/model/base_document.py", line 219, in set
    self.extend(key, value)
  File "apps/frappe/frappe/model/base_document.py", line 260, in extend
    self.append(key, v)
  File "apps/frappe/frappe/model/base_document.py", line 245, in append
    value = self._init_child(value, key)
  File "apps/frappe/frappe/model/base_document.py", line 274, in _init_child
    value = get_controller(doctype)(value)
  File "apps/frappe/frappe/model/base_document.py", line 89, in get_controller
    return _get_controller()
  File "apps/frappe/frappe/model/base_document.py", line 67, in _get_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "apps/frappe/frappe/__init__.py", line 1513, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", _load_app_hooks))
  File "apps/frappe/frappe/utils/redis_wrapper.py", line 81, in get_value
    val = generator()
  File "apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 1486, in _load_app_hooks
    print(f'Could not find app "{app}": \n{e}')
BrokenPipeError: [Errno 32] Broken pipe

